### ISSUE TITLE
Add ability to add VirtIO RNG

### ISSUE THREAD

**Issue by modem7** [hashicorp/packer-plugin-proxmox#126]
#### Community Note

Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request.
If you are interested in working on this issue or have submitted a pull request, please leave a comment.

#### Description

Proxmox has the ability to add a VirtIO RNG hardware type with configuration options. This vastly helps Linux VM's in generating entropy. 

#### Use Case(s)

Ubuntu 22.04, even though the entropy issue should have been resolved, adding this hardware type has been shown to help.

#### Potential configuration

![image](https://user-images.githubusercontent.com/4349962/203848734-7d3e0591-43e6-4bff-910e-a35da6cd14f1.png)

#### Potential References

https://wiki.qemu.org/Features/VirtIORNG

**Comment by mabeett** [comment]
Hello, 
I left a PR on the proxmox-api-go library: Telmate/proxmox-api-go#263.
The PR has been approved. 
I started working for the plugin on, now I am stalled in one validation point which is described in the PR (Draft) #195.
