### ISSUE TITLE
Disk naming convention

### ISSUE THREAD

**Issue by modem7** [hashicorp/packer-plugin-proxmox#133]
#### Overview of the Issue

When creating a disk using the ISO builder, the naming convention seems to be:

```
storage_pool:vmid/base-vmid-disk
```

Whereas as standard in Proxmox, if you create a disk, it's:

```
storage_pool:vmid/vm-vmid-disk
```

scsi0 was created by Packer
scsi1 was created manually.
![image](https://user-images.githubusercontent.com/4349962/207489810-56bb6b47-23ee-43eb-b0dd-9d27733f0405.png)

### Plugin and Packer version

Packer v1.8.5

### Simplified Packer Buildfile

```hcl
    disks {
        disk_size = "15G"
        format = "qcow2"
        storage_pool = "Proxmox"
        storage_pool_type = "directory"
        type = "scsi"
        cache_mode = "writethrough"
        io_thread = "true"
    }
```
Full config: https://paste.modem7.com/J6pmw-32Iu6
Variables: https://paste.modem7.com/8oMCY-GpDpj

Would it make more sense to have the naming convention set to "vm" instead of "base"? Unsure if this is something I've configured somehow or a default somewhere.

### Operating system and Environment details

Ubuntu, x86

**Comment by sebastian-de** [comment]
It's not a bug, it's a feature 😉

When a VM is turned into a template, Proxmox renames all disk volumes to `base-*`.
Config snippet from `/etc/pve/qemu-server/<vmid>.conf`:
```
name: template
scsi0: local-zfs:base-106-disk-0,size=2G
template: 1
```

If you create a linked clone from that template, your configuration will look like this:
```
name: linked-clone-vm
scsi0: local-zfs:base-106-disk-0/vm-107-disk-1,size=2G
```

If you create a full clone, the volume gets a regular name again:
```
name: full-clone-vm
scsi0: local-zfs:vm-108-disk-1,size=2G
```
So Packer is working as intended here.

**Comment by modem7** [comment]
Thanks for the explanation! Makes sense!
