### ISSUE TITLE
Stop restricting storage_pool_type

### ISSUE THREAD

**Issue by Iggle** [hashicorp/packer-plugin-proxmox#138]
Please search the existing issues for relevant feature requests, and use the
reaction feature
(https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/)
to add upvotes to pre-existing requests.

#### Community Note

Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request.
If you are interested in working on this issue or have submitted a pull request, please leave a comment.

#### Description

Currently, the disk storage pool types (ceph, lvm, zfs, ...) are [restricted](https://github.com/hashicorp/packer-plugin-proxmox/blob/e1bd001ca32b73debf32dca1d04c0af2920a9ff8/builder/proxmox/common/config.go#L225) due to an old [check](https://github.com/Telmate/proxmox-api-go/blob/ee6f6d6dda19cc1c34c0698e87dacc28a0386af2/proxmox/config_qemu.go#L950) in the API client. As of the currently used version, that check is [no longer present](https://github.com/Telmate/proxmox-api-go/blob/bb95d9a81e7ad16ef8300db8c29505eea58aed50/proxmox/config_qemu.go#L19). In fact, the client authors Terraform provider [no longer requires](https://registry.terraform.io/providers/Telmate/proxmox/latest/docs/resources/vm_qemu#disk-block) providing the storage_pool_type at all.

I suggest removing the restriction or at least expanding the current check to encompass the types included in the [PVE documentation](https://pve-lab-1.lab.m.secunet.de:8006/pve-docs/chapter-pvesm.html#_storage_types).

#### Use Case(s)

Storing templates in shared storage other than ceph.

**Comment by sebastian-de** [comment]
That's a good point - I missed that while updating `proxmox-api-go`. I'll have a look if we can deprecate `storage_pool_type` as well.

**Comment by theblop** [comment]
indeed I have the same problem with a "drbd" storage backend. I have to provision images on a local disk first and then use a post script to move the final image to the right storage location.

**Comment by sebastian-de** [comment]
I had a closer look at this today. Packer passes this attribute to `proxmox-api-go` as `storage_type` here: https://github.com/hashicorp/packer-plugin-proxmox/blob/9c39e973d748dd64a914217103cbe9c56d0af3bd/builder/proxmox/common/step_start_vm.go#L274

It seems that `proxmox-api-go` used `storage_type` to decide how disk images were created. This option never really was passed on to the PVE API.

The only conditional that used `storage_type` was dropped with this commit: https://github.com/Telmate/proxmox-api-go/pull/96/commits/ee27c74acdfb008a89c24852762e2d7e618495dd#diff-5fdc6257b8fc2f669960 93cf8c4b417399ba5917ca536cf74d877d6e93feec03L975

So we can safely remove `storage_pool_type` from Packer.
