### ISSUE TITLE
No VM ID given fails

### ISSUE THREAD

**Issue by ckdarby** [hashicorp/packer-plugin-proxmox#140]
#### Overview of the Issue
When using the proxmox-clone and not providing a vmid it'll fail with the following error

```bash

==> proxmox-clone.autogenerated_1: Creating ephemeral key pair for SSH communicator...
==> proxmox-clone.autogenerated_1: Created ephemeral SSH key pair for communicator
==> proxmox-clone.autogenerated_1: Creating VM
==> proxmox-clone.autogenerated_1: No VM ID given, getting next free from Proxmox
==> proxmox-clone.autogenerated_1: Get "192.168.88.62/cluster/nextid": unsupported protocol scheme ""
Build 'proxmox-clone.autogenerated_1' errored after 15 milliseconds 543 microseconds: Get "192.168.88.62/cluster/nextid": unsupported protocol scheme ""

```

#### Reproduction Steps
Create a proxmox-clone source with the minimum required fields and not provide a vmid

### Plugin and Packer version
Packer v1.8.5
github.com/hashicorp/proxmox/packer-plugin-proxmox_v1.1.0_x5.0_linux_amd64

### Simplified Packer Buildfile

An example
```hcl
source "proxmox-clone" "autogenerated_1" {
  clone_vm                 = "debian-10-4"
  cores                    = 1
  insecure_skip_tls_verify = true
  memory                   = 2048
  network_adapters {
    bridge = "vmbr0"
  }
  node                 = "pve"
  os                   = "l26"
  token             = "${var.proxmox_password}"
  pool                 = "api-users"
  proxmox_url          = "${var.proxmox_url}"
  sockets              = 1
  template_description = "image made from cloud-init image"
  template_name        = "debian-scaffolding"
  username             = "${var.proxmox_username}"
  ssh_username         = "${var.ssh_username}"
}

build {
  description = "A template for building a base"

  sources = ["source.proxmox-clone.autogenerated_1"]

}
```

### Operating system and Environment details
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.1 LTS
Release:	22.04
Codename:	jammy

**Comment by ckdarby** [comment]
The plugin should probably be using the API endpoint. Looking at the  [promox API docs ](https://pve.proxmox.com/pve-docs/api-viewer/#/cluster/nextid) it appears to be
`GET /api2/json/cluster/nextid`

**Comment by sebastian-de** [comment]
`proxmox_url` must be something like `https://192.168.1.50:8006/api2/json` - maybe the part `api2/json` is missing in your case.

**Comment by ckdarby** [comment]
Thanks. That was not clear at all to me :cry:
