### ISSUE TITLE
Unused raw disk

### ISSUE THREAD

**Issue by modem7** [hashicorp/packer-plugin-proxmox#145]
#### Overview of the Issue

When creating Packer build with latest version, a new disk is created which is unused. 

#### Reproduction Steps

```hcl
  disks {
    disk_size = "${var.vm_disk_size}"
    format = "${var.vm_format}"
    storage_pool = "${var.vm_storage_pool}"
    storage_pool_type = "${var.vm_storage_pool_type}"
    type = "${var.vm_type}"
    cache_mode = "${var.vm_cache_mode}"
    io_thread = "${var.vm_io_thread}"
  }
```

![image](https://user-images.githubusercontent.com/4349962/214140870-7978d53f-3a6f-458e-af6a-303bb70c9c14.png)

### Plugin and Packer version

Packer v1.8.5
Plugin v1.1.1

### Simplified Packer Buildfile

Packer build:
https://paste.modem7.com/62MoM-pWJrI

Packer variables:
https://paste.modem7.com/xLNnK-mbfw7

### Logs
`PACKER_LOG=1` does not give any additional information beyond:
```
❯ packer build .
ubuntu-server-jammy.proxmox-iso.ubuntu-server-jammy: output will be in this color.

==> ubuntu-server-jammy.proxmox-iso.ubuntu-server-jammy: Creating VM
==> ubuntu-server-jammy.proxmox-iso.ubuntu-server-jammy: No VM ID given, getting next free from Proxmox
==> ubuntu-server-jammy.proxmox-iso.ubuntu-server-jammy: Starting VM
==> ubuntu-server-jammy.proxmox-iso.ubuntu-server-jammy: Starting HTTP server on port 8811
==> ubuntu-server-jammy.proxmox-iso.ubuntu-server-jammy: Waiting 10s for boot
```

### Operating system and Environment details

Ubuntu 22.04.1 x64

**Comment by sebastian-de** [comment]
Hmm, I'm pretty sure it's because of this block:
https://github.com/hashicorp/packer-plugin-proxmox/blob/1fd436eb2c84430e77df37be34f3876e0e203e31/builder/proxmox/common/step_start_vm.go#L128

Proxmox seems to behave very inconsistently when it comes to creating EFI-disks. I'll see if I can fine-tune this.

**Comment by sebastian-de** [comment]
I tested several cases:

1. proxmox-iso with EFI disk in config -> unused disk
2. proxmox-iso without EFI disk in config -> OK
3. proxmox-clone without EFI disk in config nd no EFI disk in cloned VM -> OK
4. proxmox-clone with EFI disk in config and no EFI disk in cloned VM -> OK
5. proxmox-clone with EFI disk in config and existing EFI disk in cloned VM -> unused disk

Commenting out the SetVmConfig() block mentionoed above yields:
1. proxmox-iso with EFI disk in config -> OK
2. proxmox-iso without EFI disk in config -> OK
3. proxmox-clone without EFI disk in config nd no EFI disk in cloned VM -> OK
4. proxmox-clone with EFI disk in config and no EFI disk in cloned VM -> no EFI disk
5. proxmox-clone with EFI disk in config and existing EFI disk in cloned VM -> OK

I'll have to piece this together and work on a solution to get EFI disks created reliably.
