### ISSUE TITLE
efi_config creates duplicate Unused Disk 

### ISSUE THREAD

**Issue by wilddev65** [hashicorp/packer-plugin-proxmox#155]
#### Overview of the Issue

When using the plugin to create an EFI Disk for a Windows 2022 guest it appears from the debug that the creation of the EFI disk is run twice and a duplicate disk is created as 'Unused Disk 0'.

#### Reproduction Steps

1) Add the new configuration items to hcl file;
  efi_config {
    efi_storage_pool  = "VMs"
    efi_type          = "4m"
    pre_enrolled_keys = "true"
  }
2) Run the packer build command
3) VM created in Proxmox has duplicate disk of size 528k

### Plugin and Packer version

Packer v1.8.5/packer-plugin-proxmox v1.1.1

### Simplified Packer Buildfile

// Source definitions for Proxmox iso template
source "proxmox-iso" "proxmox-iso-template" {

  // Proxmox connection settings
  proxmox_url          = "${var.proxmox_api_url}"
  username             = "${var.proxmox_api_token_id}"
  token                = "${var.proxmox_api_token_secret}"
  insecure_skip_tls_verify = "true"

  // VM General settings
  node                 = "${var.proxmox_node}"
  vm_name              = "${var.vm-name}"
  vm_id                = "${var.vm-id}"
  template_description = "Windows 2022 GUI"
  boot_wait            = "2s"
  boot_command         = ["<spacebar><spacebar>"]

  // VM ISO Settings
  iso_file             = "${var.os_iso_path}"
  iso_checksum         = "${var.checksum}"
  unmount_iso          = "true"

  // Driver and extra files iso settings
  additional_iso_files {
    device       = "sata0"
    iso_checksum = "${var.add1_checksum}"
    iso_file     = "${var.add1_iso_path}"
    unmount      = "true"
  }
  additional_iso_files {
    device       = "sata1"
    iso_checksum = "${var.add2_checksum}"
    iso_file     = "${var.add2_iso_path}"
    unmount      = "true"
  }

  // VM Hardware settings
  memory          = "${var.vm-mem-size}"
  cores           = "${var.vm-cpu-num}"
  cpu_type        = "host"
  bios            = "ovmf"
  machine         = "q35"

  efi_config {
    efi_storage_pool  = "VMs"
    efi_type          = "4m"
    pre_enrolled_keys = "true"
  }

  scsi_controller      = "virtio-scsi-single"
  disks {
    disk_size         = "${var.vm-disk-size}"
    format            = "qcow2"
    io_thread         = "true"
    storage_pool      = "VMs"
    storage_pool_type = "directory"
    type              = "scsi"
  }

  network_adapters {
    bridge   = "vmbr0"
    firewall = "true"
    model    = "virtio"
    vlan_tag = "165"
  }

  //Options settings
  os           = "win11"
  qemu_agent   = "true"

}

build {
  sources = ["source.proxmox-iso.proxmox-iso-template"]

}

### Operating system and Environment details

Proxmox 7.3-4
Windows Server 2022 Guest

### Log Fragments and crash.log files

Relevant debug log entries;
1) First request sent to Proxmox to create VM
2023/02/10 09:36:00 packer-plugin-proxmox_v1.1.1_x5.0_darwin_amd64 plugin: 2023/02/10 09:36:00 >>>>>>>>>> REQUEST:
2023/02/10 09:36:00 packer-plugin-proxmox_v1.1.1_x5.0_darwin_amd64 plugin: POST /api2/json/nodes/pve1/qemu HTTP/1.1
2023/02/10 09:36:00 packer-plugin-proxmox_v1.1.1_x5.0_darwin_amd64 plugin: Host: pve1.example.net:8006
2023/02/10 09:36:00 packer-plugin-proxmox_v1.1.1_x5.0_darwin_amd64 plugin: User-Agent: Go-http-client/1.1
2023/02/10 09:36:00 packer-plugin-proxmox_v1.1.1_x5.0_darwin_amd64 plugin: Content-Length: 461
2023/02/10 09:36:00 packer-plugin-proxmox_v1.1.1_x5.0_darwin_amd64 plugin: Accept: application/json
2023/02/10 09:36:00 packer-plugin-proxmox_v1.1.1_x5.0_darwin_amd64 plugin: Authorization: PVEAPIToken=root@pam!packer=<sensitive>
2023/02/10 09:36:00 packer-plugin-proxmox_v1.1.1_x5.0_darwin_amd64 plugin: Content-Type: application/x-www-form-urlencoded
2023/02/10 09:36:00 packer-plugin-proxmox_v1.1.1_x5.0_darwin_amd64 plugin: Accept-Encoding: gzip
2023/02/10 09:36:00 packer-plugin-proxmox_v1.1.1_x5.0_darwin_amd64 plugin: 
2023/02/10 09:36:00 packer-plugin-proxmox_v1.1.1_x5.0_darwin_amd64 plugin: agent=1&bios=ovmf&cores=2&cpu=host&description=Packer+ephemeral+build+VM&efidisk0=VMs%3A1%2Cefitype%3D4m%2Cpre-enrolled-keys%3D1&ide2=local%3Aiso%2Fwindows_server2022_proxmox_noprompt.iso%2Cmedia%3Dcdrom&kvm=1&machine=q35&memory=4096&name=Win2022-Template&net0=virtio%3DDA%3A3E%3A49%3A12%3A18%3A35%2Cbridge%3Dvmbr0%2Ctag%3D165%2Cfirewall%3Dtrue&onboot=0&ostype=win11&scsi0=VMs%3A32%2Cformat%3Dqcow2%2Ciothread%3Dtrue&scsihw=virtio-scsi-single&sockets=1&vmid=110
2023/02/10 09:36:00 packer-plugin-proxmox_v1.1.1_x5.0_darwin_amd64 plugin: 2023/02/10 09:36:00 <<<<<<<<<< RESULT:
2023/02/10 09:36:00 packer-plugin-proxmox_v1.1.1_x5.0_darwin_amd64 plugin: HTTP/1.1 200 OK
2023/02/10 09:36:00 packer-plugin-proxmox_v1.1.1_x5.0_darwin_amd64 plugin: Connection: close
2023/02/10 09:36:00 packer-plugin-proxmox_v1.1.1_x5.0_darwin_amd64 plugin: Content-Length: 77
2023/02/10 09:36:00 packer-plugin-proxmox_v1.1.1_x5.0_darwin_amd64 plugin: Cache-Control: max-age=0
2023/02/10 09:36:00 packer-plugin-proxmox_v1.1.1_x5.0_darwin_amd64 plugin: Content-Type: application/json;charset=UTF-8
2023/02/10 09:36:00 packer-plugin-proxmox_v1.1.1_x5.0_darwin_amd64 plugin: Date: Fri, 10 Feb 2023 16:36:00 GMT
2023/02/10 09:36:00 packer-plugin-proxmox_v1.1.1_x5.0_darwin_amd64 plugin: Expires: Fri, 10 Feb 2023 16:36:00 GMT
2023/02/10 09:36:00 packer-plugin-proxmox_v1.1.1_x5.0_darwin_amd64 plugin: Pragma: no-cache
2023/02/10 09:36:00 packer-plugin-proxmox_v1.1.1_x5.0_darwin_amd64 plugin: Server: pve-api-daemon/3.0
2023/02/10 09:36:00 packer-plugin-proxmox_v1.1.1_x5.0_darwin_amd64 plugin: 
2023/02/10 09:36:00 packer-plugin-proxmox_v1.1.1_x5.0_darwin_amd64 plugin: {"data":"UPID:pve1:002478ED:04702FD7:63E67270:qmcreate:110:root@pam!packer:"}

2) Second request sent to Proxmox to create efidisk 
2023/02/10 09:36:10 packer-plugin-proxmox_v1.1.1_x5.0_darwin_amd64 plugin: 2023/02/10 09:36:10 >>>>>>>>>> REQUEST:
2023/02/10 09:36:10 packer-plugin-proxmox_v1.1.1_x5.0_darwin_amd64 plugin: POST /api2/json/nodes/pve1/qemu/110/config HTTP/1.1
2023/02/10 09:36:10 packer-plugin-proxmox_v1.1.1_x5.0_darwin_amd64 plugin: Host: pve1.example.net:8006
2023/02/10 09:36:10 packer-plugin-proxmox_v1.1.1_x5.0_darwin_amd64 plugin: User-Agent: Go-http-client/1.1
2023/02/10 09:36:10 packer-plugin-proxmox_v1.1.1_x5.0_darwin_amd64 plugin: Content-Length: 55
2023/02/10 09:36:10 packer-plugin-proxmox_v1.1.1_x5.0_darwin_amd64 plugin: Accept: application/json
2023/02/10 09:36:10 packer-plugin-proxmox_v1.1.1_x5.0_darwin_amd64 plugin: Authorization: PVEAPIToken=root@pam!packer=<sensitive>
2023/02/10 09:36:10 packer-plugin-proxmox_v1.1.1_x5.0_darwin_amd64 plugin: Content-Type: application/x-www-form-urlencoded
2023/02/10 09:36:10 packer-plugin-proxmox_v1.1.1_x5.0_darwin_amd64 plugin: Accept-Encoding: gzip
2023/02/10 09:36:10 packer-plugin-proxmox_v1.1.1_x5.0_darwin_amd64 plugin: 
2023/02/10 09:36:10 packer-plugin-proxmox_v1.1.1_x5.0_darwin_amd64 plugin: efidisk0=VMs%3A1%2Cefitype%3D4m%2Cpre-enrolled-keys%3D1
2023/02/10 09:36:10 packer-plugin-proxmox_v1.1.1_x5.0_darwin_amd64 plugin: 2023/02/10 09:36:10 <<<<<<<<<< RESULT:
2023/02/10 09:36:10 packer-plugin-proxmox_v1.1.1_x5.0_darwin_amd64 plugin: HTTP/1.1 200 OK
2023/02/10 09:36:10 packer-plugin-proxmox_v1.1.1_x5.0_darwin_amd64 plugin: Connection: close
2023/02/10 09:36:10 packer-plugin-proxmox_v1.1.1_x5.0_darwin_amd64 plugin: Content-Length: 77
2023/02/10 09:36:10 packer-plugin-proxmox_v1.1.1_x5.0_darwin_amd64 plugin: Cache-Control: max-age=0
2023/02/10 09:36:10 packer-plugin-proxmox_v1.1.1_x5.0_darwin_amd64 plugin: Content-Type: application/json;charset=UTF-8
2023/02/10 09:36:10 packer-plugin-proxmox_v1.1.1_x5.0_darwin_amd64 plugin: Date: Fri, 10 Feb 2023 16:36:10 GMT
2023/02/10 09:36:10 packer-plugin-proxmox_v1.1.1_x5.0_darwin_amd64 plugin: Expires: Fri, 10 Feb 2023 16:36:10 GMT
2023/02/10 09:36:10 packer-plugin-proxmox_v1.1.1_x5.0_darwin_amd64 plugin: Pragma: no-cache
2023/02/10 09:36:10 packer-plugin-proxmox_v1.1.1_x5.0_darwin_amd64 plugin: Server: pve-api-daemon/3.0
2023/02/10 09:36:10 packer-plugin-proxmox_v1.1.1_x5.0_darwin_amd64 plugin: 
2023/02/10 09:36:10 packer-plugin-proxmox_v1.1.1_x5.0_darwin_amd64 plugin: {"data":"UPID:pve1:00247A7B:047033C5:63E6727A:qmconfig:110:root@pam!packer:"}

**Comment by sebastian-de** [comment]
Hey @wilddev65 , this is a duplicate of #145 and should be fixed via #147 in the next release.

**Comment by wilddev65** [comment]
Dang, my github search foo isn't great. Thanks Sebastian!
