### ISSUE TITLE
qemu_agent defaulting to false, even though default should be true

### ISSUE THREAD

**Issue by karliemeads** [hashicorp/packer-plugin-proxmox#16]
### Overview of the Issue

When creating a VM using Proxmox ISO Builder, if `qemu_agent` is left unset, the expected result is for it to default to `true`. However, it is defaulting to `false`. Tests, pass, however they should fail.
https://www.packer.io/docs/builders/proxmox/iso#qemu_agent

### Reproduction Steps
- Create a VM using Proxmox-ISO builder with `qemu_agent` set to `true`.
- Create a VM using Proxmox-ISO builder without specifying `qemu_agent`. It is expected that the agent configuration defaults to true, however it actually defaults to false. This appears to be caused by https://github.com/hashicorp/packer-plugin-proxmox/blob/main/builder/proxmox/common/config.go#L110-L119.
#### Plugin and Packer version

From `packer version`
1.7.2

#### Simplified Packer Buildfile
From Proxmox ISO builder test.
```json
{
  "builders": [
    {
      "type": "proxmox-iso",
      "proxmox_url": "https://my-proxmox.my-domain:8006/api2/json",
      "insecure_skip_tls_verify": true,
      "username": "apiuser@pve",
      "password": "supersecret",

      "node": "my-proxmox",
      "network_adapters": [
        {
          "bridge": "vmbr0"
        }
      ],
      "disks": [
        {
          "type": "scsi",
          "disk_size": "5G",
          "storage_pool": "local-lvm",
          "storage_pool_type": "lvm"
        }
      ],

      "iso_file": "local:iso/Fedora-Server-dvd-x86_64-29-1.2.iso",
      "http_directory":"config",
      "boot_wait": "10s",
      "boot_command": [
        "<up><tab> ip=dhcp inst.cmdline inst.ks=http://{{.HTTPIP}}:{{.HTTPPort}}/ks.cfg<enter>"
      ],

      "ssh_username": "root",
      "ssh_timeout": "15m",
      "ssh_password": "packer",

      "unmount_iso": true,
      "template_name": "fedora-29",
      "template_description": "Fedora 29-1.2, generated on {{ isotime \"2006-01-02T15:04:05Z\" }}"
    }
  ]
}
```
### Operating system and Environment details

Docker Container
hashicorp/packer:latest

**Comment by karliemeads** [comment]
After further testing, this issue only appears using `.pkr.hcl` file. `.json` appear to work fine. I suspect the issue is related to this line of code https://github.com/hashicorp/packer-plugin-proxmox/blob/main/builder/proxmox/iso/builder.go#L24.

**Comment by carlpett** [comment]
Hm, odd! @azr or @SwampDragons any ideas about parsing differences?

**Comment by karliemeads** [comment]
@carlpett Thanks for taking the time to originally create this plugin! I've found a solution by using the custom `config.trilean` typing, which was orginally implemented here for other plugins: https://github.com/hashicorp/packer/pull/8021.

I have working code in my main branch https://github.com/karliemeads/packer-plugin-proxmox, and just need to update tests to reflect the new proposed typing for `qemu_agent`.

I'm aiming to submit a PR to close this issue within the next day or so.
