### ISSUE TITLE
Please add MTU-Option for NIC-Configurations

### ISSUE THREAD

**Issue by SirFailBob** [hashicorp/packer-plugin-proxmox#164]
Hello everyone,
is it possible to add the MTU-Option for NIC-Configurations? We are stuggeling with creating Machines on a Proxmox tied to a SDN and therefor need a reduced MTU.
The Proxmox-UI allows for this when creating NICs.

Overall I suspect the requested feature implementation to be similar to this request: https://github.com/hashicorp/packer/issues/7856 
It resulted in the following PR: https://github.com/hashicorp/packer/pull/7862/

Best regards

**Comment by sebastian-de** [comment]
I guess this should be quite easy to add. I'll have a look at it.

**Comment by SirFailBob** [comment]
Wow @sebastian-de, that was blazing fast!
Thank you so much! <3
