### ISSUE TITLE
use ssh agent key in proxmox-iso build

### ISSUE THREAD

**Issue by camaeel** [hashicorp/packer-plugin-proxmox#192]
In the sources there is undocumented option: ssh_agent_auth.
Is it possible to utilize it to connect to ssh on the instance?

Or maybe there is an alternative way to use some one-time credentilas only for the build time instead of the static password (which is then embedded in the image and poses a security threat).

**Comment by camaeel** [comment]
This option works for iso builder. Why then it is not documented?

**Comment by skorobkov** [comment]
I am using sshkey plugin for that
```
packer {
  required_plugins {
    proxmox = {
      version = ">= 1.1.3"
      source  = "github.com/hashicorp/proxmox"
    }
    sshkey = {
      version = ">= 1.0.1"
      source  = "github.com/ivoronin/sshkey"
    }
  }
}

data "sshkey" "install" {
  name = "packer-install"
  type = "ed25519"
}

source "proxmox-iso" "OL9-kickstart" {
  ...
  http_content = {
    "/ks-ol9-cloud.cfg" = templatefile("ks-ol9-cloud.cfg.pkrtpl", {
      ssh_public_key = data.sshkey.install.public_key
    })
  }
  ssh_timeout               = "10m"
  ssh_username              = "root"
  ssh_private_key_file      = data.sshkey.install.private_key_path
  ssh_clear_authorized_keys = true
  temporary_key_pair_name   = "packer-install"
}
```

And use public key inside kickstart file template ks-ol9-cloud.cfg.pkrtpl
```
sshkey --username root "${ssh_public_key}"
```

**Comment by camaeel** [comment]
Thanx @skorobkov 
This is exactly what I needed. 

Why most of the examples on the internet hardcode password instead of going into something secure?
