### ISSUE TITLE
VMWare Fusion Ubuntu 64-bit Arm Server 22.04.3 stuck on boot

### ISSUE THREAD

**Issue by franmosmad** [hashicorp/packer-plugin-proxmox#240]
My VM was working perfectly fine until I went to start it up and it got stuck in the booting process. Here's a screenshot of where it's stuck at:

<img width="1440" alt="Screenshot 2023-11-14 at 12 49 31 AM" src="https://github.com/hashicorp/packer-plugin-proxmox/assets/139067840/7d5af9cb-9859-4083-84c3-5e8c1ba53c9b">

Can someone please help me? I have uninstalled and installed and it still does not seem to solve the problem. I am on a Macbook Pro M2 on Sonoma 14.1

**Comment by mabeett** [comment]
Hello @franmosmad 
Which version of proxmox pve are you using?
Information about packer and proxmox plugin is going to be useful also.

Is the virtual machine managed by packer?

**Comment by lbajolet-hashicorp** [comment]
Hi @franmosmad,

This looks like a question for the community more than something linked to Packer or the Proxmox plugin. Based on the title of your issue, this would be something more related to the VMWare plugin, but again, this looks outside of the tooling here.

For general questions, I would encourage you to ask your question over on our [Discuss](https://discuss.hashicorp.com/c/packer/23). Github issues are mostly for us maintainers to track feature requests or bugs with tooling, as this is not one of those, I'll close this issue, but please feel free to reopen if I missed something.

Thanks!
