### ISSUE TITLE
Can I set "args=" to specify additional arguments in the Proxmox plugin

### ISSUE THREAD

**Issue by rhpijnacker-philips** [hashicorp/packer-plugin-proxmox#243]
(Also posted this on Google Groups - https://groups.google.com/g/packer-tool/c/-8a52KYfkXA - but that seems to be filled with spam...)

Hello,

I am trying to setup deploying a macOS VM using Proxmox (legally, it is running on an old iMac, which fits Apple's license). For this I am following this guide:
https://www.youtube.com/watch?v=68R2SdbFj-8&ab_channel=i12bretro

I was able to run this manually, but since we will reinstalling the macOS instances regularly, I would like to deploy this using Packer.

One of the steps in the guide is to add an additional line in the VM conf file that has 
  args: ...
however, I do not see any means to pass this from Packer.
I looked in the Proxmox API and it seems to be a valid part of the VM config.

Did I miss something, or is this simply not supported by the Proxmox plugin?

Thanks,

Ronald

**Comment by mabeett** [comment]
Hello,
I am not part of HashiCorp so take my answer as a personal one.

The plugin interacts with Proxmox PVE via API calls, The documentation for the API is available online on https://pve.proxmox.com/pve-docs/api-viewer/index.html
For a VM configuration I guess the info should be here
https://pve.proxmox.com/pve-docs/api-viewer/index.html#/nodes/{node}/qemu/{vmid}/config

You can access the documentation for your PVE node ( specific version ) 
`https://${host}:${port}/pve-docs/api-viewer/index.html`

Warning: some webGUI or shell actions may not have API action.

Internally the plugin uses the library https://github.com/Telmate/proxmox-api-go/ so sometimes  a patch to the library is necessary.

Some of the contributors were interested on implementing certain features so in my case I added the contribution to the library, then when the patch merged PR in this repository.
