### ISSUE TITLE
iothread=1 being set on all scsi disks regardless of io_thread option

### ISSUE THREAD

**Issue by iay** [hashicorp/packer-plugin-proxmox#248]
#### Overview of the Issue

I am seeing `iothread=1` being set on disk configurations even if I explicitly request that it not be. I think this is an operator precendence error.

#### Reproduction Steps

My configuration contains this:

```
  disks {
    disk_size         = "40G"
    storage_pool      = "local-lvm"
    type              = "scsi"
    discard           = true    # may be moved to thin storage later
    io_thread         = false   # supposedly the default
  }
  scsi_controller     = "virtio-scsi-pci"
```

The disk configuration ends up as:

```
scsi0: local-lvm:base-100-disk-0,discard=on,iothread=1,size=40G
```

Proxmox complains:

```
WARN: iothread is only valid with virtio disk or virtio-scsi-single controller, ignoring
```

### Plugin and Packer version

Packer v1.10.0
Plugin 1.1.6

### Comments

I believe this is due to the following code (`step_start_vm.go` line 289):

```go
		if devs[idx]["type"] == "scsi" || devs[idx]["type"] == "virtio" &&
			disks[idx].IOThread {
			devs[idx]["iothread"] = "true"
		}
```

I'm not a Go programmer, but I think the issue here may be that the precedence of `&&` is higher than that of `||` and this is therefore being evaluated as:

```go
if devs[idx]["type"] == "scsi" ||
   (devs[idx]["type"] == "virtio" && disks[idx].IOThread) {
```

This means `iothread` is going to be set for all `scsi` disks.

I believe the fix would be:

```go
		if (devs[idx]["type"] == "scsi" || devs[idx]["type"] == "virtio") &&
			disks[idx].IOThread {
			devs[idx]["iothread"] = "true"
		}
```

This would echo the code in `proxmox-api-go` which processes this option:

```go
	if (disk.Type == scsi || disk.Type == virtIO) && disk.IOThread {
		settings = settings + ",iothread=1"
	}
```

**Comment by lbajolet-hashicorp** [comment]
Hi @iay,

Good catch! Thanks for reporting this.

I've opened a PR to fix this problem, running the test I added does exhibit the behaviour you describe, and adding the parentheses as you suggested to fix the operator priority does fix that.
