### ISSUE TITLE
Add aio disk configuration available

### ISSUE THREAD

**Issue by Nekasas** [hashicorp/packer-plugin-proxmox#257]
#### Description

To have a proper golden image we need to set **aio = "native"** which is not the default configuration in Proxmox. Please add this feature

#### Use Case(s)

**aio = native** is way faster than default Proxmox **io_uring** configuration

**Comment by lbajolet-hashicorp** [comment]
Hey @Nekasas,

Thanks for reporting this.

Would you be able to submit a patch to the plugin for supporting this by chance?
Otherwise we'll try to look into it, but we cannot make a commitment as to when this will be supported.

**Comment by Nekasas** [comment]
Hi, I am not an expert in programming so it would be better if someone else could take a look into this.  I noticed that this plugin is using Telmate Proxmox API code and Telmate already has "aio" functionality. 

https://github.com/Telmate/terraform-provider-proxmox

**Comment by mpywell** [comment]
Some of the groundwork for adding AsyncIO settings is in the config uplift in #260, happy to pick up and submit as a separate PR after it's merged.
