### ISSUE TITLE
Add shutdown command. 

### ISSUE THREAD

**Issue by DevTown** [hashicorp/packer-plugin-proxmox#268]
Please search the existing issues for relevant feature requests, and use the
reaction feature
(https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/)
to add upvotes to pre-existing requests.

#### Community Note

Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request.
If you are interested in working on this issue or have submitted a pull request, please leave a comment.

#### Description

For my Windows images it would be nice to have the possibility to set a shutdown-command.
At the moment i can not use the full potential with packer and proxmox because i have to manually fire the command for sysprep my windows image. After that the image shutdown and i have ti manually convert it to a template because the normal shutdown with packer cant let me use a sysprep. So i would like to have the possibility to set my own command to shutdown the vm like in other plugins like for HyperV

#### Use Case(s)

sysprep the windowsimage to use it later as a copy source.

**Comment by lbajolet-hashicorp** [comment]
Hi @DevTown,

This looks to me as feasible with a shell script, doesn't it? I'm not sure what Hyper-V does in terms of shutdown command, but as far as the Proxmox builder goes, it's platform agnostic, so setting a shutdown command is out of scope of this plugin imo.

You're probably better off using the `powershell` provisioner to do this, and have the script perform the shutdown once sysprep has finished executing (iirc the command goes in the background when you invoke it, but you can probably watch the process until it finishes).

**Comment by DevTown** [comment]
I will strip the script down to the min tomorrow and will post it here. :)

**Comment by DevTown** [comment]
Ok while i am cutting down the script i found the bug in there that is the problem packer will not wait for "ending" it :-( 
It seams the script is not a script it is a call for a scheduled task and because of this the script finished and packer shuts down the vm. I fixed this and now everything works like expected. Sorry for confusing and thx for your responses.
