### ISSUE TITLE
Allow adding serial sockets to template

### ISSUE THREAD

**Issue by nerok** [hashicorp/packer-plugin-proxmox#41]
#### Description

We can add "serial0" as the vga display type, but as far as I can tell there isn't any way to create serial0 in packer.

#### Use Case(s)

This would allow configurations of serial ports for the template. Proxmox allows port 0-3 it seems.

#### Potential configuration

```
serial_port [0, 1, 3]
```

#### Potential References
Proxmox has a page about Serial Terminal here: https://pve.proxmox.com/wiki/Serial_Terminal

**Comment by DblK** [comment]
Adding serial port in some distribution is excepted for some cloud-init distribution.
Would be great to have it. Any news on it?

**Comment by scholdan** [comment]
Any news on it?
