### ISSUE TITLE
Add support for "TPM State" option for system

### ISSUE THREAD

**Issue by gihov** [hashicorp/packer-plugin-proxmox#73]
#### Description

Allow to set the "TPM" flag with  version and storage if enable, when building images using this plugin. The version is by default "v2.0" but can be "v1.2".

#### Use Case(s)

Enabling this option allow user to get access to Windows11 VM on proxmox, since it require TPM to be installed.

#### Potential configuration

```json
"os": "win11",
"machine": "q35",
"bios": "ovmf",
"efidisk": "local",
"tpm": true,
"tpm_storage": "local"
```
`tpm_version: "v1.2"` if needed but staying on v2.0 by default.

#### Potential References

Proxmox documentation (section 10.2.11) : https://pve.proxmox.com/pve-docs/pve-admin-guide.html#qm_virtual_machines_settings
It looks like `qm set <vmid> -tpmstate0 <storage>:1,version=<version>` currently to set TPM on proxmox.

**Comment by alexanderek** [comment]
any news?

**Comment by woloss** [comment]
Looks like `proxmox-api-go` still without TPM part, therefore no functionality for terraform, packer.

However, would be nice to be able to make W11 template or W2022 with vTPM in near future.

**Comment by altmeista** [comment]
> Looks like `proxmox-api-go` still without TPM part, therefore no functionality for terraform, packer.
> 
> However, would be nice to be able to make W11 template or W2022 with vTPM in near future.

There's a workaround for windows machines like windows 11 by adding a registry entry via the autounattend.xml file during install process. Works for me by now, but TPM support would be better of course.

**Comment by newedgex** [comment]
This is a must for windows 11 builds

**Comment by TuncTaylan** [comment]
Pinging...

**Comment by Puben** [comment]
Also here to show my interest in adding support for TPM using the Proxmox builder.

**Comment by mac641** [comment]
Also waiting for this to be added...

**Comment by niliopoulos89** [comment]
also waiting for this...

**Comment by ChrisDek** [comment]
+1 to the list of people who need to build real windows 11 machines without any hacks, so I need vTPM support in the builder. The vsphere-iso builder has this for a long time now

**Comment by vonMort** [comment]
+1 for this. A really needed improvement.

**Comment by FMRZDK** [comment]
+1 really needed here.

**Comment by R8bit** [comment]
+1 same here, would love to see this finally added

**Comment by mpywell** [comment]
Just submitted a PR to upstream telmate-api-go for TPM support. If merged happy to take a run at implementing TPM here.
https://github.com/Telmate/proxmox-api-go/issues/241

**Comment by Torqu3Wr3nch** [comment]
Great work, @mpywell! This release is shaping up to have some great new features for the Proxmox builder.
