### ISSUE TITLE
Use SCSI controller for Cloud-Init

### ISSUE THREAD

**Issue by DerEnderKeks** [hashicorp/packer-plugin-proxmox#74]
#### Community Note

Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request.
If you are interested in working on this issue or have submitted a pull request, please leave a comment.

#### Description

Cloud-init drives should be attached to a SCSI controller instead of an IDE controller.

#### Use Case(s)

RHEL 8 doesn't support (some?) IDE drives anymore, causing Cloud-Init to abort while starting, since the Cloud-init drive is missing.

#### Potential configuration

\-

#### Potential References

https://bugs.centos.org/view.php?id=16898

**Comment by 53845714nF** [comment]
I have a similar problem. Get an CD/DVD (ide2) but I want an CloudInit Drive (scsi0).
Cd/DVD is not recognized as CloudInit Drive in proxmox.

Packer: 1.8.5
Proxmox: 7.3-3
