### ISSUE TITLE
overwrite existing template image.

### ISSUE THREAD

**Issue by fanuelsen** [hashicorp/packer-plugin-proxmox#76]
I'm trying to make a repeatable pipeline and get packer to overwrite the image I'm making if its already exist. I can do this on the VMware-iso builder with applying -force when building templates. Is there a option for this in the proxmox builder? When I try to build the vm again it complains about the vmid already existing.

Error creating VM: Error creating VM: 500 unable to create VM 100 - VM 100 already exists. 

I would like to be able to overwrite to build templates with newly installed updates and so on...

**Comment by mizhka** [comment]
Disclaimer: i'm ordinary user of packer plugin for proxmox, not member of maintainer team.
I'm not 100% sure that my understanding of issue is correct.
Normally plugin allows to recreate template, but with different ID. So it's better to rename old template for backup purpose, then build new template and remove old image if not needed anymore.

**Comment by adrian-hoasted** [comment]
There should be an overwrite or a force option.

**Comment by fanuelsen** [comment]
Yes, when i use -force i would expect that it should overwrite the current template even if the ID exist.
